#!/bin/bash

# check if the number of arguments is correct
if (( $# != 1 )); then
    echo "Usage: $0 <input_file>"
    exit 1
fi
input_file=$1
temp_folder="country_data"
country_count=0

# create a temporary folder to store data for each country
mkdir -p $temp_folder

# read the header of the input file
awk -F '\t' 'NR > 1 && $8 != "" {print > ("'${temp_folder}'/" $1 ".tsv")}' $input_file


# for each country, calculate the correlation between the Cantril ladder score and each of the other columns
for country_file in ${temp_folder}/*.tsv; do
    awk -f correlation.awk -v COL1=4 -v COL2=8 "$country_file" >> ${temp_folder}/GDP_with_Cantril_ladder.txt
    awk -f correlation.awk -v COL1=5 -v COL2=8 "$country_file" >> ${temp_folder}/Population_with_Cantril_ladder.txt
    awk -f correlation.awk -v COL1=6 -v COL2=8 "$country_file" >> ${temp_folder}/Homicide_Rate_with_Cantril_ladder.txt
    awk -f correlation.awk -v COL1=7 -v COL2=8 "$country_file" >> ${temp_folder}/Life_Expectancy_with_Cantril_ladder.txt
    #country_count=$((country_count+1))
done

# calculate the mean of the correlation values for each predictor
awk -f mean.awk ${temp_folder}/GDP_with_Cantril_ladder.txt > value.txt
awk -f mean.awk ${temp_folder}/Population_with_Cantril_ladder.txt >> value.txt
awk -f mean.awk ${temp_folder}/Homicide_Rate_with_Cantril_ladder.txt >> value.txt
awk -f mean.awk ${temp_folder}/Life_Expectancy_with_Cantril_ladder.txt >> value.txt

# compare the absolute values of the correlation values for each predictor
awk -f compare.awk value.txt >> value.txt

# print the result on terminal
cat value.txt




# remove the temporary folder
rm -r $temp_folder
rm -r value.txt

#awk -f correlation.awk -v COL1=4 COL2=8 sample2.tsv
