#!/bin/bash

# check if the number of arguments is correct
if [ $# -ne 3 ]; then
    echo "Usage: $0 file1 file2 file3"
    exit 1
fi
#
check_rows(){
    local count1=$(wc -l < "$1")
    local count2=$(wc -l < "$2")
    local count3=$(wc -l < "$3")
    local min=$count1
    local minfile=$1

    if [ $count2 -lt $min ]; then
        min=$count2
        minfile=$2
    fi 

    if [ $count3 -lt $min ]; then
        min=$count3
        minfile=$3
    fi

    echo $minfile
}

minfile=$(check_rows "$1" "$2" "$3")
#echo "The file with the fewest rows is $minfile"

awk -F'\t' '$2 != "" {print $1"\t"$2"\t"$3"\t"}' $minfile > min.txt 
# Generate the file with the fewest rows and remove rows where the second column is empty

#add gdp column
awk 'BEGIN {FS=OFS="\t"}

# Read and store the first and second columns of the first file
FNR==NR {
    keys[$1,$2,$3] = 1;
    next;
}

# Process the second file, find matches and output the GDP column
($1,$2,$3) in keys {
    if ($5) {
        print $1, $2, $3, $5;  # Print matching records with the GDP column
    } else {
        print $1, $2, $3, $5;  # Print matching records with the GDP column
        print $2, $3, "gdp lost" > "/dev/stderr";  # Print $2 and $3 to stderr if $5 does not exist
    }
}' min.txt gdp-vs-happiness.tsv > temp0.txt

#add Population column
awk 'BEGIN {FS=OFS="\t"}
# store columns as keys
FNR==NR {
    keys[$1,$2,$3] = $4;
    next;
}

# add Population column
($1,$2,$3) in keys {
    if ($6) {
        print $1, $2, $3, keys[$1, $2, $3], $6;
    } else {
        print $1, $2, $3, keys[$1, $2, $3], $6;
        print $2, $3, "population lost" > "/dev/stderr";
    }

}' temp0.txt gdp-vs-happiness.tsv > temp1.txt

#homicide-rate
awk 'BEGIN {FS=OFS="\t"}

# store columns as keys
FNR==NR {
    keys[$1,$2,$3] = $1 OFS $2 OFS $3 OFS $4 OFS $5;
    next;
}

# add homicide-rate column and check if it is empty
($1,$2,$3) in keys {
   if ($4>0) {
        print keys[$1,$2,$3], $4;
    }
     else {
        print keys[$1,$2,$3], $4;
        print $2, $3, "homicide-rate lost" > "/dev/stderr";
    }
}' temp1.txt homicide-rate-unodc.tsv > temp2.txt

#Life expectancy
awk 'BEGIN {FS=OFS="\t"}
FNR==NR {
    keys[$1,$2,$3] = $1 OFS $2 OFS $3 OFS $4 OFS $5 OFS $6;
    next;
}
($1,$2,$3) in keys {
    if ($4) {
        print keys[$1,$2,$3], $4;
    } else {
        print keys[$1,$2,$3], $4;
        print $2, $3, "life-expectancy lost" > "/dev/stderr";
    }
}' temp2.txt life-satisfaction-vs-life-expectancy.tsv > temp3.txt

#Cantril Ladder
awk 'BEGIN {FS=OFS="\t"}
FNR==NR {
    keys[$1,$2,$3] = $1 OFS $2 OFS $3 OFS $4 OFS $5 OFS $6 OFS $7;
    next;
}
($1,$2,$3) in keys && $4 != ""{
    if ($4) {
        print keys[$1,$2,$3], $4;
    } else {
        print keys[$1,$2,$3], $4;
        print $2, $3, "Cantril Ladder lost" > "/dev/stderr";
    }
}' temp3.txt gdp-vs-happiness.tsv > temp4.tsv

cat temp4.tsv
#remove temp files
rm min.txt temp0.txt temp1.txt temp2.txt temp3.txt temp4.tsv

